version: 2

updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: daily
    time: "05:00"
  commit-message:
    prefix: "[docker] "
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:00"
  commit-message:
    prefix: "[github-actions] "
  open-pull-requests-limit: 10

- package-ecosystem: gomod
  directory: "/backend"
  schedule:
    interval: daily
    time: "05:00"
  commit-message:
    prefix: "[gomod] "
  open-pull-requests-limit: 10

- package-ecosystem: "npm"
  directory: "/frontend"
  schedule:
    interval: daily
    time: "05:00"
  commit-message:
    prefix: "[npm] "
  open-pull-requests-limit: 10
