version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.41.0
    ports:
      - 14250:14250
      - 14268:14268
      - 16686:16686
    volumes:
      - jaeger-data:/jaeger

volumes:
  jaeger-data:
