version: '3.8'

services:
  postgres:
    image: postgres:15.1
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
