version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./backend/schema.mysql.sql:/docker-entrypoint-initdb.d/schema.sql
