// Code generated by MockGen. DO NOT EDIT.
// Source: internal/entity/manager/principal.go

// Package manager is a generated GoMock package.
package manager

import (
	reflect "reflect"

	model "github.com/eko/authz/backend/internal/entity/model"
	repository "github.com/eko/authz/backend/internal/entity/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockPrincipal is a mock of Principal interface.
type MockPrincipal struct {
	ctrl     *gomock.Controller
	recorder *MockPrincipalMockRecorder
}

// MockPrincipalMockRecorder is the mock recorder for MockPrincipal.
type MockPrincipalMockRecorder struct {
	mock *MockPrincipal
}

// NewMockPrincipal creates a new mock instance.
func NewMockPrincipal(ctrl *gomock.Controller) *MockPrincipal {
	mock := &MockPrincipal{ctrl: ctrl}
	mock.recorder = &MockPrincipalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrincipal) EXPECT() *MockPrincipalMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPrincipal) Create(identifier string, roles []string, attributes map[string]any) (*model.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", identifier, roles, attributes)
	ret0, _ := ret[0].(*model.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPrincipalMockRecorder) Create(identifier, roles, attributes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPrincipal)(nil).Create), identifier, roles, attributes)
}

// Delete mocks base method.
func (m *MockPrincipal) Delete(identifier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", identifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPrincipalMockRecorder) Delete(identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPrincipal)(nil).Delete), identifier)
}

// GetRepository mocks base method.
func (m *MockPrincipal) GetRepository() repository.Principal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepository")
	ret0, _ := ret[0].(repository.Principal)
	return ret0
}

// GetRepository indicates an expected call of GetRepository.
func (mr *MockPrincipalMockRecorder) GetRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepository", reflect.TypeOf((*MockPrincipal)(nil).GetRepository))
}

// Update mocks base method.
func (m *MockPrincipal) Update(identifier string, roles []string, attributes map[string]any) (*model.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", identifier, roles, attributes)
	ret0, _ := ret[0].(*model.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPrincipalMockRecorder) Update(identifier, roles, attributes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPrincipal)(nil).Update), identifier, roles, attributes)
}
